// This file was generated by SquareLine Studio (and subsequently modified)
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h" // Should include lvgl.h and all other ui_*.h files
#include "ui_artificial_horizon_widget.h" // Our custom widget header

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Artificial_Horizon_Page;
lv_obj_t *ui_ArtificialHorizonPageLabel; // Label for the page title
lv_obj_t *ui_Page2HomeBTN;
lv_obj_t *ui_HomeBTN1; // Label for Home button
lv_obj_t *ui_Page2PrevBTN;
lv_obj_t *ui_Page2PrevBTN1; // Label for Prev button
lv_obj_t *ui_Page2NextBTN2; // Button object for Next
lv_obj_t *ui_Page2NextBTN;  // Label for Next button
// lv_obj_t *ui_Label5; // This seemed to be a duplicate title label in the original, using ui_ArtificialHorizonPageLabel instead

// CUSTOM VARIABLES for Artificial Horizon
lv_obj_t *uic_ArtificialHorizon; // The container object for the AHRS, declared in .h
static ui_ahrs_widget_t ahrs_data; // Static data structure for our AHRS widget
static lv_timer_t *ahrs_update_timer = NULL; // Timer for updating the AHRS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// EVENT HANDLER FUNCTIONS (from original logic) ////////////////////
void ui_event_Page2HomeBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_RELEASED) {
        // Original action: _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Options_Page_screen_init);
        // Adjusted to a more common animation for "Home" if preferred, or keep original.
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Options_Page_screen_init);
    }
}

void ui_event_Page2PrevBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Bubble_Level_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Bubble_Level_Page_screen_init);
    }
}

void ui_event_Page2NextBTN2(lv_event_t * e) // Corresponds to ui_Page2NextBTN2 object
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Shot_Counter_Page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Shot_Counter_Page_screen_init);
    }
}

///////////////////// CUSTOM WIDGET FUNCTIONS ////////////////////
// Timer callback function to update the artificial horizon
static void update_artificial_horizon_widget_timer_cb(lv_timer_t *timer) {
    update_artificial_horizon_widget(&ahrs_data);
}

///////////////////// SCREEN INIT ////////////////////
void ui_Artificial_Horizon_Page_screen_init(void)
{
    ui_Artificial_Horizon_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Artificial_Horizon_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Main Page Label
    ui_ArtificialHorizonPageLabel = lv_label_create(ui_Artificial_Horizon_Page);
    lv_obj_set_width(ui_ArtificialHorizonPageLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_ArtificialHorizonPageLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_ArtificialHorizonPageLabel, 0);
    lv_obj_set_y(ui_ArtificialHorizonPageLabel, -110); // Adjusted Y from original for consistency
    lv_obj_set_align(ui_ArtificialHorizonPageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArtificialHorizonPageLabel, "Artificial Horizon");

    // Container for the Artificial Horizon (uic_ArtificialHorizon)
    // This ensures uic_ArtificialHorizon is a dedicated container for the AHRS widget.
    if (!uic_ArtificialHorizon) { 
        uic_ArtificialHorizon = lv_obj_create(ui_Artificial_Horizon_Page);
    }
    lv_obj_set_width(uic_ArtificialHorizon, 160);
    lv_obj_set_height(uic_ArtificialHorizon, 120);
    lv_obj_set_x(uic_ArtificialHorizon, 0);
    lv_obj_set_y(uic_ArtificialHorizon, -10); 
    lv_obj_set_align(uic_ArtificialHorizon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(uic_ArtificialHorizon, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(uic_ArtificialHorizon, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(uic_ArtificialHorizon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(uic_ArtificialHorizon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create the artificial horizon widget inside the container
    // Using hardcoded 160, 120 as per our troubleshooting
    create_artificial_horizon_widget(uic_ArtificialHorizon, &ahrs_data, 160, 120);

    // Create and start the timer for AHRS updates
    if (ahrs_update_timer) {
        lv_timer_del(ahrs_update_timer);
        ahrs_update_timer = NULL;
    }
    ahrs_update_timer = lv_timer_create(update_artificial_horizon_widget_timer_cb, 50, NULL);


    // Home Button
    ui_Page2HomeBTN = lv_btn_create(ui_Artificial_Horizon_Page);
    lv_obj_set_width(ui_Page2HomeBTN, 50);
    lv_obj_set_height(ui_Page2HomeBTN, 25);
    lv_obj_set_x(ui_Page2HomeBTN, -60);
    lv_obj_set_y(ui_Page2HomeBTN, 85);
    lv_obj_set_align(ui_Page2HomeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page2HomeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page2HomeBTN, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(ui_Page2HomeBTN, ui_event_Page2HomeBTN, LV_EVENT_RELEASED, NULL); // Use LV_EVENT_RELEASED

    ui_HomeBTN1 = lv_label_create(ui_Page2HomeBTN);
    lv_label_set_text(ui_HomeBTN1, "HOME"); // Original text was "HOME"
    lv_obj_set_align(ui_HomeBTN1, LV_ALIGN_CENTER); // Center label on button

    // Previous Button
    ui_Page2PrevBTN = lv_btn_create(ui_Artificial_Horizon_Page);
    lv_obj_set_width(ui_Page2PrevBTN, 50);
    lv_obj_set_height(ui_Page2PrevBTN, 25);
    lv_obj_set_x(ui_Page2PrevBTN, 0); 
    lv_obj_set_y(ui_Page2PrevBTN, 85); 
    lv_obj_set_align(ui_Page2PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page2PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);    
    lv_obj_clear_flag(ui_Page2PrevBTN, LV_OBJ_FLAG_SCROLLABLE);     
    lv_obj_add_event_cb(ui_Page2PrevBTN, ui_event_Page2PrevBTN, LV_EVENT_RELEASED, NULL); // Use LV_EVENT_RELEASED

    ui_Page2PrevBTN1 = lv_label_create(ui_Page2PrevBTN);
    lv_label_set_text(ui_Page2PrevBTN1, "PREV"); // Original text was "PREV"
    lv_obj_set_align(ui_Page2PrevBTN1, LV_ALIGN_CENTER);

    // Next Button
    ui_Page2NextBTN2 = lv_btn_create(ui_Artificial_Horizon_Page);
    lv_obj_set_width(ui_Page2NextBTN2, 50);
    lv_obj_set_height(ui_Page2NextBTN2, 25);
    lv_obj_set_x(ui_Page2NextBTN2, 60); 
    lv_obj_set_y(ui_Page2NextBTN2, 85);  
    lv_obj_set_align(ui_Page2NextBTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page2NextBTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);    
    lv_obj_clear_flag(ui_Page2NextBTN2, LV_OBJ_FLAG_SCROLLABLE);      
    lv_obj_add_event_cb(ui_Page2NextBTN2, ui_event_Page2NextBTN2, LV_EVENT_RELEASED, NULL); // Use LV_EVENT_RELEASED

    ui_Page2NextBTN = lv_label_create(ui_Page2NextBTN2); 
    lv_label_set_text(ui_Page2NextBTN, "NEXT"); // Original text was "NEXT"
    lv_obj_set_align(ui_Page2NextBTN, LV_ALIGN_CENTER);

    // Note: The original file had `uic_ArtificialHorizon = ui_Artificial_Horizon_Page;`
    // This has been omitted as uic_ArtificialHorizon is now a dedicated container object.
    // The original file also had `ui_Label5` as a title, which seems redundant with `ui_ArtificialHorizonPageLabel`.
}

// Screen destroy function, includes AHRS widget cleanup
void ui_Artificial_Horizon_Page_screen_destroy(void)
{
    // Delete the timer
    if (ahrs_update_timer) {
        lv_timer_del(ahrs_update_timer);
        ahrs_update_timer = NULL;
    }

    // Destroy AHRS widget custom data (e.g., canvas buffer)
    destroy_artificial_horizon_widget(&ahrs_data);

    // The original destroy function deleted ui_Artificial_Horizon_Page and nulled all pointers.
    // This is usually handled by the main screen changing logic in ui.c or ui_helpers.c
    // when _ui_screen_change is called. If this function is *only* for this screen's
    // specific cleanup before the generic screen deletion, then the above is sufficient.
    // If this function IS the one deleting the screen object, then:
    // if(ui_Artificial_Horizon_Page) {
    //     lv_obj_del(ui_Artificial_Horizon_Page);
    //     ui_Artificial_Horizon_Page = NULL;
    //     uic_ArtificialHorizon = NULL; // Also nullify our custom container pointer
    //     // Nullify other pointers if this function is responsible for full cleanup
    // }
}
