// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Bubble_Level_Page;
lv_obj_t * ui_BubbleLevelPageLabel;
lv_obj_t * ui_Page1HomeBTN;
lv_obj_t * ui_Pg1HomeBTN;
lv_obj_t * ui_Page1NextBTN1;
lv_obj_t * ui_Page1NextBTN;
lv_obj_t * ui_Page1PrevBTN;
lv_obj_t * ui_Page1PrevBTN1;

// event funtions
void ui_event_Page1HomeBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Options_Page_screen_init);
    }
}

void ui_event_Page1NextBTN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Artificial_Horizon_Page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0,
                          &ui_Artificial_Horizon_Page_screen_init);
    }
}

void ui_event_Page1PrevBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Options_Page_screen_init);
    }
}

// build funtions

void ui_Bubble_Level_Page_screen_init(void)
{
    ui_Bubble_Level_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Bubble_Level_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BubbleLevelPageLabel = lv_label_create(ui_Bubble_Level_Page);
    lv_obj_set_width(ui_BubbleLevelPageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BubbleLevelPageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BubbleLevelPageLabel, 0);
    lv_obj_set_y(ui_BubbleLevelPageLabel, -110);
    lv_obj_set_align(ui_BubbleLevelPageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BubbleLevelPageLabel, "Bubble Level");

    ui_Page1HomeBTN = lv_btn_create(ui_Bubble_Level_Page);
    lv_obj_set_width(ui_Page1HomeBTN, 50);
    lv_obj_set_height(ui_Page1HomeBTN, 25);
    lv_obj_set_x(ui_Page1HomeBTN, -60);
    lv_obj_set_y(ui_Page1HomeBTN, 85);
    lv_obj_set_align(ui_Page1HomeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page1HomeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page1HomeBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pg1HomeBTN = lv_label_create(ui_Page1HomeBTN);
    lv_obj_set_width(ui_Pg1HomeBTN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pg1HomeBTN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pg1HomeBTN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pg1HomeBTN, "HOME");

    ui_Page1NextBTN1 = lv_btn_create(ui_Bubble_Level_Page);
    lv_obj_set_width(ui_Page1NextBTN1, 50);
    lv_obj_set_height(ui_Page1NextBTN1, 25);
    lv_obj_set_x(ui_Page1NextBTN1, 60);
    lv_obj_set_y(ui_Page1NextBTN1, 85);
    lv_obj_set_align(ui_Page1NextBTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page1NextBTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page1NextBTN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page1NextBTN = lv_label_create(ui_Page1NextBTN1);
    lv_obj_set_width(ui_Page1NextBTN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page1NextBTN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page1NextBTN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page1NextBTN, "NEXT");

    ui_Page1PrevBTN = lv_btn_create(ui_Bubble_Level_Page);
    lv_obj_set_width(ui_Page1PrevBTN, 50);
    lv_obj_set_height(ui_Page1PrevBTN, 25);
    lv_obj_set_x(ui_Page1PrevBTN, 0);
    lv_obj_set_y(ui_Page1PrevBTN, 85);
    lv_obj_set_align(ui_Page1PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page1PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page1PrevBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page1PrevBTN1 = lv_label_create(ui_Page1PrevBTN);
    lv_obj_set_width(ui_Page1PrevBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page1PrevBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page1PrevBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page1PrevBTN1, "PREV");

    lv_obj_add_event_cb(ui_Page1HomeBTN, ui_event_Page1HomeBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page1NextBTN1, ui_event_Page1NextBTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page1PrevBTN, ui_event_Page1PrevBTN, LV_EVENT_ALL, NULL);

}

void ui_Bubble_Level_Page_screen_destroy(void)
{
    if(ui_Bubble_Level_Page) lv_obj_del(ui_Bubble_Level_Page);

    // NULL screen variables
    ui_Bubble_Level_Page = NULL;
    ui_BubbleLevelPageLabel = NULL;
    ui_Page1HomeBTN = NULL;
    ui_Pg1HomeBTN = NULL;
    ui_Page1NextBTN1 = NULL;
    ui_Page1NextBTN = NULL;
    ui_Page1PrevBTN = NULL;
    ui_Page1PrevBTN1 = NULL;

}
