// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Competition_Page;
lv_obj_t * ui_CompPageLabel;
lv_obj_t * ui_Page5HomeBTN;
lv_obj_t * ui_Page5HomeBTN1;
lv_obj_t * ui_Page5PrevBTN;
lv_obj_t * ui_Page5PrevBTN1;
lv_obj_t * ui_Page5NextBTN;
lv_obj_t * ui_Page5NextBTN1;

// event funtions
void ui_event_Page5HomeBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Options_Page_screen_init);
    }
}

void ui_event_Page5PrevBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Stage_Timer_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Stage_Timer_Page_screen_init);
    }
}

void ui_event_Page5NextBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Options_Page_screen_init);
    }
}

// build funtions

void ui_Competition_Page_screen_init(void)
{
    ui_Competition_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Competition_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CompPageLabel = lv_label_create(ui_Competition_Page);
    lv_obj_set_width(ui_CompPageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompPageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompPageLabel, 0);
    lv_obj_set_y(ui_CompPageLabel, -110);
    lv_obj_set_align(ui_CompPageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompPageLabel, "Competition");

    ui_Page5HomeBTN = lv_btn_create(ui_Competition_Page);
    lv_obj_set_width(ui_Page5HomeBTN, 50);
    lv_obj_set_height(ui_Page5HomeBTN, 25);
    lv_obj_set_x(ui_Page5HomeBTN, -60);
    lv_obj_set_y(ui_Page5HomeBTN, 85);
    lv_obj_set_align(ui_Page5HomeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page5HomeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page5HomeBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page5HomeBTN1 = lv_label_create(ui_Page5HomeBTN);
    lv_obj_set_width(ui_Page5HomeBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page5HomeBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page5HomeBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page5HomeBTN1, "HOME");

    ui_Page5PrevBTN = lv_btn_create(ui_Competition_Page);
    lv_obj_set_width(ui_Page5PrevBTN, 50);
    lv_obj_set_height(ui_Page5PrevBTN, 25);
    lv_obj_set_x(ui_Page5PrevBTN, 0);
    lv_obj_set_y(ui_Page5PrevBTN, 85);
    lv_obj_set_align(ui_Page5PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page5PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page5PrevBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page5PrevBTN1 = lv_label_create(ui_Page5PrevBTN);
    lv_obj_set_width(ui_Page5PrevBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page5PrevBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page5PrevBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page5PrevBTN1, "PREV");

    ui_Page5NextBTN = lv_btn_create(ui_Competition_Page);
    lv_obj_set_width(ui_Page5NextBTN, 50);
    lv_obj_set_height(ui_Page5NextBTN, 25);
    lv_obj_set_x(ui_Page5NextBTN, 60);
    lv_obj_set_y(ui_Page5NextBTN, 85);
    lv_obj_set_align(ui_Page5NextBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page5NextBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page5NextBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page5NextBTN1 = lv_label_create(ui_Page5NextBTN);
    lv_obj_set_width(ui_Page5NextBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page5NextBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page5NextBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page5NextBTN1, "NEXT");

    lv_obj_add_event_cb(ui_Page5HomeBTN, ui_event_Page5HomeBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page5PrevBTN, ui_event_Page5PrevBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page5NextBTN, ui_event_Page5NextBTN, LV_EVENT_ALL, NULL);

}

void ui_Competition_Page_screen_destroy(void)
{
    if(ui_Competition_Page) lv_obj_del(ui_Competition_Page);

    // NULL screen variables
    ui_Competition_Page = NULL;
    ui_CompPageLabel = NULL;
    ui_Page5HomeBTN = NULL;
    ui_Page5HomeBTN1 = NULL;
    ui_Page5PrevBTN = NULL;
    ui_Page5PrevBTN1 = NULL;
    ui_Page5NextBTN = NULL;
    ui_Page5NextBTN1 = NULL;

}
