// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_COMPETITION_PAGE_H
#define UI_COMPETITION_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Competition_Page
extern void ui_Competition_Page_screen_init(void);
extern void ui_Competition_Page_screen_destroy(void);
extern lv_obj_t * ui_Competition_Page;
extern lv_obj_t * ui_CompPageLabel;
extern void ui_event_Page5HomeBTN(lv_event_t * e);
extern lv_obj_t * ui_Page5HomeBTN;
extern lv_obj_t * ui_Page5HomeBTN1;
extern void ui_event_Page5PrevBTN(lv_event_t * e);
extern lv_obj_t * ui_Page5PrevBTN;
extern lv_obj_t * ui_Page5PrevBTN1;
extern void ui_event_Page5NextBTN(lv_event_t * e);
extern lv_obj_t * ui_Page5NextBTN;
extern lv_obj_t * ui_Page5NextBTN1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

