// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Shot_Counter_Page;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Page3HomeBTN;
lv_obj_t * ui_Page3HomeBTN1;
lv_obj_t * ui_Page3PrevBTN;
lv_obj_t * ui_Page3PrevBTN1;
lv_obj_t * ui_Page3NextBTN;
lv_obj_t * ui_Page3NextBTN1;

// event funtions
void ui_event_Page3HomeBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Options_Page_screen_init);
    }
}

void ui_event_Page3PrevBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Artificial_Horizon_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0,
                          &ui_Artificial_Horizon_Page_screen_init);
    }
}

void ui_event_Page3NextBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Stage_Timer_Page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Stage_Timer_Page_screen_init);
    }
}

// build funtions

void ui_Shot_Counter_Page_screen_init(void)
{
    ui_Shot_Counter_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Shot_Counter_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -110);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Shot Counter");

    ui_Page3HomeBTN = lv_btn_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_Page3HomeBTN, 50);
    lv_obj_set_height(ui_Page3HomeBTN, 25);
    lv_obj_set_x(ui_Page3HomeBTN, -60);
    lv_obj_set_y(ui_Page3HomeBTN, 85);
    lv_obj_set_align(ui_Page3HomeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page3HomeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page3HomeBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page3HomeBTN1 = lv_label_create(ui_Page3HomeBTN);
    lv_obj_set_width(ui_Page3HomeBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page3HomeBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page3HomeBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page3HomeBTN1, "HOME");

    ui_Page3PrevBTN = lv_btn_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_Page3PrevBTN, 50);
    lv_obj_set_height(ui_Page3PrevBTN, 25);
    lv_obj_set_x(ui_Page3PrevBTN, 0);
    lv_obj_set_y(ui_Page3PrevBTN, 85);
    lv_obj_set_align(ui_Page3PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page3PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page3PrevBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page3PrevBTN1 = lv_label_create(ui_Page3PrevBTN);
    lv_obj_set_width(ui_Page3PrevBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page3PrevBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page3PrevBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page3PrevBTN1, "PREV");

    ui_Page3NextBTN = lv_btn_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_Page3NextBTN, 50);
    lv_obj_set_height(ui_Page3NextBTN, 25);
    lv_obj_set_x(ui_Page3NextBTN, 60);
    lv_obj_set_y(ui_Page3NextBTN, 85);
    lv_obj_set_align(ui_Page3NextBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page3NextBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page3NextBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page3NextBTN1 = lv_label_create(ui_Page3NextBTN);
    lv_obj_set_width(ui_Page3NextBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page3NextBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page3NextBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page3NextBTN1, "Next");

    lv_obj_add_event_cb(ui_Page3HomeBTN, ui_event_Page3HomeBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page3PrevBTN, ui_event_Page3PrevBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page3NextBTN, ui_event_Page3NextBTN, LV_EVENT_ALL, NULL);

}

void ui_Shot_Counter_Page_screen_destroy(void)
{
    if(ui_Shot_Counter_Page) lv_obj_del(ui_Shot_Counter_Page);

    // NULL screen variables
    ui_Shot_Counter_Page = NULL;
    ui_Label6 = NULL;
    ui_Page3HomeBTN = NULL;
    ui_Page3HomeBTN1 = NULL;
    ui_Page3PrevBTN = NULL;
    ui_Page3PrevBTN1 = NULL;
    ui_Page3NextBTN = NULL;
    ui_Page3NextBTN1 = NULL;

}
