// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STAGE_TIMER_PAGE_H
#define UI_STAGE_TIMER_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Stage_Timer_Page
extern void ui_Stage_Timer_Page_screen_init(void);
extern void ui_Stage_Timer_Page_screen_destroy(void);
extern lv_obj_t * ui_Stage_Timer_Page;
extern lv_obj_t * ui_SrageTimerPageLabel;
extern void ui_event_Page4HomeBTN(lv_event_t * e);
extern lv_obj_t * ui_Page4HomeBTN;
extern lv_obj_t * ui_Page4HomeBTN1;
extern void ui_event_Page4PrevBTN(lv_event_t * e);
extern lv_obj_t * ui_Page4PrevBTN;
extern lv_obj_t * ui_Page4PrevBTN1;
extern void ui_event_Page4NextBTN(lv_event_t * e);
extern lv_obj_t * ui_Page4NextBTN;
extern lv_obj_t * ui_Page4NextBTN1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

