// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Stage_Timer_Page;
lv_obj_t * ui_SrageTimerPageLabel;
lv_obj_t * ui_Page4HomeBTN;
lv_obj_t * ui_Page4HomeBTN1;
lv_obj_t * ui_Page4PrevBTN;
lv_obj_t * ui_Page4PrevBTN1;
lv_obj_t * ui_Page4NextBTN;
lv_obj_t * ui_Page4NextBTN1;

// event funtions
void ui_event_Page4HomeBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Options_Page_screen_init);
    }
}

void ui_event_Page4PrevBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Shot_Counter_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Shot_Counter_Page_screen_init);
    }
}

void ui_event_Page4NextBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Competition_Page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Competition_Page_screen_init);
    }
}

// build funtions

void ui_Stage_Timer_Page_screen_init(void)
{
    ui_Stage_Timer_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Stage_Timer_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SrageTimerPageLabel = lv_label_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_SrageTimerPageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SrageTimerPageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SrageTimerPageLabel, 0);
    lv_obj_set_y(ui_SrageTimerPageLabel, -110);
    lv_obj_set_align(ui_SrageTimerPageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SrageTimerPageLabel, "Stage Timer");

    ui_Page4HomeBTN = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_Page4HomeBTN, 50);
    lv_obj_set_height(ui_Page4HomeBTN, 25);
    lv_obj_set_x(ui_Page4HomeBTN, -60);
    lv_obj_set_y(ui_Page4HomeBTN, 85);
    lv_obj_set_align(ui_Page4HomeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page4HomeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page4HomeBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page4HomeBTN1 = lv_label_create(ui_Page4HomeBTN);
    lv_obj_set_width(ui_Page4HomeBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page4HomeBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page4HomeBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page4HomeBTN1, "HOME");

    ui_Page4PrevBTN = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_Page4PrevBTN, 50);
    lv_obj_set_height(ui_Page4PrevBTN, 25);
    lv_obj_set_x(ui_Page4PrevBTN, 0);
    lv_obj_set_y(ui_Page4PrevBTN, 85);
    lv_obj_set_align(ui_Page4PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page4PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page4PrevBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page4PrevBTN1 = lv_label_create(ui_Page4PrevBTN);
    lv_obj_set_width(ui_Page4PrevBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page4PrevBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page4PrevBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page4PrevBTN1, "PREV");

    ui_Page4NextBTN = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_Page4NextBTN, 50);
    lv_obj_set_height(ui_Page4NextBTN, 25);
    lv_obj_set_x(ui_Page4NextBTN, 60);
    lv_obj_set_y(ui_Page4NextBTN, 85);
    lv_obj_set_align(ui_Page4NextBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page4NextBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page4NextBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page4NextBTN1 = lv_label_create(ui_Page4NextBTN);
    lv_obj_set_width(ui_Page4NextBTN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page4NextBTN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page4NextBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page4NextBTN1, "NEXT");

    lv_obj_add_event_cb(ui_Page4HomeBTN, ui_event_Page4HomeBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page4PrevBTN, ui_event_Page4PrevBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page4NextBTN, ui_event_Page4NextBTN, LV_EVENT_ALL, NULL);

}

void ui_Stage_Timer_Page_screen_destroy(void)
{
    if(ui_Stage_Timer_Page) lv_obj_del(ui_Stage_Timer_Page);

    // NULL screen variables
    ui_Stage_Timer_Page = NULL;
    ui_SrageTimerPageLabel = NULL;
    ui_Page4HomeBTN = NULL;
    ui_Page4HomeBTN1 = NULL;
    ui_Page4PrevBTN = NULL;
    ui_Page4PrevBTN1 = NULL;
    ui_Page4NextBTN = NULL;
    ui_Page4NextBTN1 = NULL;

}
