// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SHOT_COUNTER_PAGE_H
#define UI_SHOT_COUNTER_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Shot_Counter_Page
extern void ui_Shot_Counter_Page_screen_init(void);
extern void ui_Shot_Counter_Page_screen_destroy(void);
extern lv_obj_t * ui_Shot_Counter_Page;
extern lv_obj_t * ui_Label6;
extern void ui_event_Page3HomeBTN(lv_event_t * e);
extern lv_obj_t * ui_Page3HomeBTN;
extern lv_obj_t * ui_Page3HomeBTN1;
extern void ui_event_Page3PrevBTN(lv_event_t * e);
extern lv_obj_t * ui_Page3PrevBTN;
extern lv_obj_t * ui_Page3PrevBTN1;
extern void ui_event_Page3NextBTN(lv_event_t * e);
extern lv_obj_t * ui_Page3NextBTN;
extern lv_obj_t * ui_Page3NextBTN1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

